version: '3.8'
services:
  api:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - 3000:3000
    command: sh docker-entrypoint.sh
    volumes:
      - .:/usr/app/
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/test?schema=public
    depends_on:
      - 'postgres'
    env_file:
      - .env

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test

volumes:
  postgres:
    name: nest-db


